### ISSUE TITLE
Language not being passed to pacman

### ISSUE THREAD

**Issue by SelfMadeSystem** [fosskers/aura#767] opened 2022-05-26 04:55 UTC
I set my system language to `fr_CA.UTF-8`. Aura and pacman both use their french translations, however when pacman is called through aura (I think), it defaults to english.

![image](https://user-images.githubusercontent.com/38010540/170418654-6c4f2335-71fc-43a8-8e99-4604daa4c453.png)

It's not a major issue for me since I speak English (obviously), but I think other people might find it more serious.

Edit: I don't know if it's a config issue for me or what, but all my applications are in french so ¯\\\_(ツ)_/¯

Edit 2: It's also annoying because the confirmation prompt in french is [O/n] for [Oui/non], but in english it's [Y/n] for [Yes/no] and it's probably worse in other languages.

**Comment by fosskers** [comment] 2022-05-26 16:33
For 10 years I've waited for someone to report this :laughing: 

I suspect it's due to how environment variables are inherited (or not) by `pacman` when called through Aura. Since the Rust Port works a little differently, I'll make sure this is fixed there.

**Comment by True-cc** [comment] 2022-05-26 16:58
for 10 years lmao 😂

so you knew about this? this kinda funi

welp thx 4 fixing it in rust port

**Comment by fosskers** [comment] 2022-05-26 17:00
Specifically I was waiting for someone to complain that Aura's language flags (like `--french`) don't affect `pacman`.

**Comment by True-cc** [comment] 2022-05-26 17:07
It's especially annoying because the confirmation prompt in french is [O/n] (Oui/non) but in English it's [Y/n] (Your/nose) <details>joke!!! ik [Y/n] is (Yes/no)</details>

**Comment by PRESFIL** [comment] 2023-07-20 17:36
Duplicate of #720

**Comment by fosskers** [comment] 2024-06-27 21:36
Using Aura 4 (soon to be released), I just built several packages with my system locale set to `fr_CA.UTF-8`, and everything worked without issue. I recently ported all the localisations from Aura 3 to 4, including [French](https://github.com/fosskers/aura/commit/c71d6a8a4009f4a7a47483df66ebad76db164e27).

I'm sorry that it took me so long to address this.

**Closed by fosskers** 2024-06-27 21:36 UTC
Labels: bug
