### ISSUE TITLE
 When delmakedeps = true base-devel package not removing

### ISSUE THREAD

**Issue by utrumo** [fosskers/aura#910] opened 2024-08-14 08:34 UTC
I set delmakedeps = true in ~/.config/aura/config.toml

After building and installing the package from aur, aura asks me to remove all make dependencies, but skips base-devel

**Comment by fosskers** [comment] 2024-08-14 10:23
This is by design. `base-devel` is automatically added if missing, and according to AUR policy is always assumed to be installed when building AUR packages.

**Comment by utrumo** [comment] 2024-08-14 16:13
It's a pity, I expected from this flag that it would completely clean up all dev dependencies.
But at the same time, aura -Oj removes this package.

**Comment by fosskers** [comment] 2024-08-14 20:35
What would the advantage be to removing it and readding it each time you do an install?

**Comment by fosskers** [comment] 2024-08-24 01:22
Any thoughts on this?

**Comment by fosskers** [comment] 2024-09-08 04:51
I'm going to close this for now. Please feel free to reopen it if there's anything further regarding this that you'd like to discuss.

**Closed by fosskers** 2024-09-08 04:51 UTC
