### ISSUE TITLE
auto-skip of conflict resolution on AUR packages

### ISSUE THREAD

**Issue by RubenKelevra** [fosskers/aura#867] opened 2024-07-31 13:02 UTC
I'm currently using Aura 4.0.0 (git version) and attempted to install the standard version.

These two packages are clearly in conflict, but instead of prompting me to confirm the removal of the aura-git package, the conflict resolution is being skipped automatically:

```
$ aura -A aura
aura :: Determining dependencies...
aura :: Repository dependencies:
 aura
aura :: AUR packages:
aura :: Proceed? [Y/n] y
resolving dependencies...
looking for conflicting packages...
:: aura-3.2.9-1 and aura-git-4.0.0.r0.geaac6297-1 are in conflict. Remove aura-git? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: aura-3.2.9-1 and aura-git-4.0.0.r0.geaac6297-1 are in conflict
aura :: A call to pacman -S failed.

```

**Comment by fosskers** [comment] 2024-07-31 20:35
Someone else mentioned this yesterday in the AUR comments but I was unable to reproduce. 
```
error: unresolvable package conflicts detected
```
Did you enter `y` into the prompt, or press `Enter`? If `Enter`, it would have cancelled it.

**Comment by RubenKelevra** [comment] 2024-08-01 18:13
Nope, I did nothing, it just runs through the question without any action by me.

Have a look:

[Screencast_20240801_201018_.webm](https://github.com/user-attachments/assets/19997f05-81d6-4782-8ec0-047c3147794e)

**Comment by fosskers** [comment] 2024-08-01 21:19
Ah notice that it's detecting `aura` as a _repo_ dependency, not an AUR one. This must be due to usage of Cachy. I just checked again and it doesn't occur when `aura` is built from the AUR. In which case this is a duplicate of #801 , and I will close this in favour of that.

**Closed by fosskers** 2024-08-01 21:19 UTC
