### ISSUE TITLE
 aura >>= As of makepkg v4.2, building as root is no longer possible.

### ISSUE THREAD

**Issue by rogue-agent** [fosskers/aura#815] opened 2023-09-20 10:37 UTC
Hello world,

I didn't find anything similar? So I'll post it here.
I'm trying to install a package from aur but I get the following error. What can we do?

`➜  ~ doas aura -A js8call
aura >>= As of makepkg v4.2, building as root is no longer possible.       
➜  ~ aura -A js8call
aura >>= You cannot perform this operation without using sudo.`

**Comment by CowCowFuture** [comment] 2023-09-20 15:26
#680

**Comment by fosskers** [comment] 2023-09-21 01:42
Unfortunately Aura does not yet support `doas`. We hope to rectify this in Aura 4.

**Comment by fosskers** [comment] 2023-09-21 01:42
Closing as a duplicate of #680

**Closed by fosskers** 2023-09-21 01:42 UTC
