### ISSUE TITLE
aura tries to download the source code before the --hotedit flag is triggered

### ISSUE THREAD

**Issue by utrumo** [fosskers/aura#896] opened 2024-08-10 12:27 UTC
When installing cryptopro-csp-k1, aura tries to download the source code before the --hotedit flag is triggered.

Expected behavior:
First, open PKGBUILD for editing, at this moment i
 download linux-amd64.tgz and put it to in $HOME/.cache/aura/builds/cryptopro-csp-k1 and later continue the installation.

It works for me with paru, but with aura I get the following error, regardless of whether I put linux-amd64.tgz or not next to PKGBUILD

log:
```
aura :: AUR packages to upgrade:
 cryptopro-csp-k1 :: 5.0.12900-3 -> 5.0.13000-1
aura :: Determining dependencies...
aura :: AUR packages:
 cryptopro-csp-k1
aura :: Proceed? [Y/n] y
aura :: Saved package state.
aura :: Preparing build directories...
aura :: Building cryptopro-csp-k1...
aura :: Package failed to build, citing:

  Failed to copy build files.

aura :: Action cancelled.
```

**Comment by utrumo** [comment] 2024-08-10 12:37
I bypassed the problem as follows:
I downloaded and put linux-amd64.tgz in $HOME/.cache/aura/builds/cryptopro-csp-k1

Then he performed:
makepkg -s
aura -U cryptopro-csp-k1-5.0.13000-1-x86_64.pkg.tar.zst

**Comment by AladW** [comment] 2024-08-10 14:44
It seems the `--hotedit` flag doesn't do anything anymore.

**Comment by fosskers** [comment] 2024-08-11 12:21
> It seems the --hotedit flag doesn't do anything anymore.

It certainly does, but I will debug this. Note that `~/.cache/aura/packages/` is an entirely pure place, all building and hotediting, etc., happens in `~/.cache/aura/builds/`.

**Comment by pushcx** [comment] 2024-08-11 18:08
I think `--hotedit` is maybe firing at the wrong step for a different reason:

```
~ $ sudo -E aura -A --hotedit obs-studio-git
aura :: Determining dependencies...
aura :: The dependency obs-studio-git of ffnvcodec-headers< does not exist.
```

I am trying to hotedit to [correct that dependency](https://aur.archlinux.org/packages/obs-studio-git#comment-979529) but I can't edit because the dependency is incorrect.

**Comment by fosskers** [comment] 2024-08-12 03:21
See also [this section of the Guide](https://fosskers.github.io/aura/aur.html#altering-the-pkgbuild-before-building).

**Comment by pushcx** [comment] 2024-08-12 13:58
Thanks, I had missed that sentence of the manual. I agree that my concern is a dupe of #605. Maybe `aura` should hint `--skipdepcheck` or link to that part of the manual if its dep check fails when running with `--hotedit`.

**Comment by fosskers** [comment] 2024-08-24 01:53
Note there is a special notice in the original package in question (`cryptopro-csp-k1`):
```
# En
# ==
# This PKGBUILD does not automatically download CSP archive because
# accessing it requires logging in. Please download the archive manually
# and place alongside the PKGBUILD before building. Link:
```
So it makes sense that the file copy would fail. I'll close this ticket.

**Closed by fosskers** 2024-08-24 01:53 UTC
Labels: bug?
